[tool.ruff]
line-length = 119
select = ["ALL"]
target-version = "py311"
ignore = [
  "ANN", "COM", "CPY", "EM",
  "D100", "D200", "D203", "D212",
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191", "E501", "D206", "Q000", "Q001", "Q002", "Q003", "ISC001",
  "C901",  # ... is too complex
  "D103",  # Missing docstring in public function
  "PLR0915",  # Too many statements
  "PLR2004",  # Magic value used
  "PTH116",  # os.stat()
  "S101",  # Use of `assert` detected
  "S603",  # subprocess
  "S607",  # partial executable path
  "S113",  # requests timeout
  "S301",  # pickle
  "S310",  # Audit URL open for permitted schemes
  "S320",  # Using `lxml` to parse untrusted data
  "TRY003",  # Avoid specifying long messages outside the exception class
]
